type SeedShop = {
  id: string;
  name: string;
  slug: string;
  address: string;
  city: string;
  metro: 'dfw' | 'austin';
  lat: number;
  lng: number;
  website: string | null;
  instagram: string | null;
};

type SeedArtist = {
  id: string;
  name: string;
  slug: string;
  instagram: string | null;
  acceptingClients: boolean;
  styles: string[]; /** Style slugs, resolved to ids by the seed. */
  shopSlugs: string[]; /** Shop slugs; the first is treated as primary. */
};

export const STYLE_LABELS: Record<string, string> = {
  traditional: 'Traditional',
  japanese: 'Japanese',
  'fine-line': 'Fine line',
  blackwork: 'Blackwork',
  realism: 'Realism',
  'neo-traditional': 'Neo-traditional',
  geometric: 'Geometric',
  lettering: 'Lettering',
  illustrative: 'Illustrative',
  color: 'Color',
};

const shop = (
  sequence: number,
  fields: Omit<SeedShop, 'id' | 'website' | 'instagram'> &
    Partial<Pick<SeedShop, 'website' | 'instagram'>>,
): SeedShop => ({
  id: `11111111-1111-4111-8111-${String(sequence).padStart(12, '0')}`,
  website: null,
  instagram: null,
  ...fields,
});

const artist = (
  sequence: number,
  fields: Omit<SeedArtist, 'id' | 'instagram' | 'acceptingClients'> &
    Partial<Pick<SeedArtist, 'instagram' | 'acceptingClients'>>,
): SeedArtist => ({
  id: `33333333-3333-4333-8333-${String(sequence).padStart(12, '0')}`,
  instagram: null,
  acceptingClients: true,
  ...fields,
});

export const SHOPS: SeedShop[] = [
  // ── Dallas proper ─────────────────────────────────────────────
  shop(1, {
    name: 'Elm Street Tattoo',
    slug: 'elm-street-tattoo',
    address: '2811 Elm St, Dallas, TX 75226',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.78492,
    lng: -96.78324,
    website: 'https://www.elmstreettattoo.com',
  }),
  shop(2, {
    name: 'Gold Dust Tattoos & Fine Art',
    slug: 'gold-dust-tattoos',
    address: '1902 Greenville Ave, Dallas, TX 75206',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.81286,
    lng: -96.77004,
  }),
  shop(3, {
    name: 'Dallas Tattoo & Arts Company',
    slug: 'dallas-tattoo-arts-company',
    address: '2712 Live Oak St, Dallas, TX 75204',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.78868,
    lng: -96.78912,
  }),
  shop(4, {
    name: 'Cedar Springs Tattoo & Piercing',
    slug: 'cedar-springs-tattoo',
    address: '4008 Cedar Springs Rd, Dallas, TX 75219',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.8112,
    lng: -96.81128,
  }),
  shop(5, {
    name: 'Eden Body Art Studio',
    slug: 'eden-body-art-studio',
    address: '13360 Preston Rd, Dallas, TX 75240',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.93065,
    lng: -96.80347,
  }),
  shop(6, {
    name: 'Rebel Muse Tattoo',
    slug: 'rebel-muse-tattoo',
    address: '17370 Preston Rd, Dallas, TX 75252',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.99017,
    lng: -96.8008,
  }),
  shop(7, {
    name: 'Third Eye Gallery',
    slug: 'third-eye-gallery',
    address: '2025 E Levee St, Dallas, TX 75207',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.79026,
    lng: -96.8259,
  }),
  shop(8, {
    name: 'Koneko Studio',
    slug: 'koneko-studio',
    address: '3901 Main St, Dallas, TX 75226',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.78676,
    lng: -96.77303,
  }),
  shop(9, {
    name: 'Pristine Ink',
    slug: 'pristine-ink',
    address: '114 Parkhouse St, Dallas, TX 75207',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.78344,
    lng: -96.81885,
  }),
  shop(10, {
    name: 'Lady Magnolia',
    slug: 'lady-magnolia',
    address: '1801 Laws St, Dallas, TX 75202',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.78286,
    lng: -96.80541,
  }),
  shop(11, {
    name: 'Folklore Trading Co',
    slug: 'folklore-trading-co',
    address: '3120 Swiss Ave, Dallas, TX 75204',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.78959,
    lng: -96.78413,
  }),
  shop(12, {
    name: 'Singleton Tattoo',
    slug: 'singleton-tattoo',
    address: '437 Singleton Blvd, Dallas, TX 75212',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.77877,
    lng: -96.8318,
  }),
  shop(13, {
    name: 'Artistic Encounter',
    slug: 'artistic-encounter',
    address: '3417 Main St, Dallas, TX 75226',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.78555,
    lng: -96.77593,
  }),
  shop(14, {
    name: 'Sinners Tattoo Studio',
    slug: 'sinners-tattoo-studio',
    address: '5032 Lemmon Ave, Dallas, TX 75209',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.82371,
    lng: -96.81912,
  }),
  shop(15, {
    name: 'Legacy Arts Tattoo',
    slug: 'legacy-arts-tattoo',
    address: '13021 Coit Rd, Dallas, TX 75240',
    city: 'Dallas',
    metro: 'dfw',
    lat: 32.92605,
    lng: -96.76978,
  }),

  // ── DFW suburbs ───────────────────────────────────────────────
  shop(16, {
    name: 'Allegiance Tattoo',
    slug: 'allegiance-tattoo',
    address: '4716 E Lake Highlands Dr Ste 110, The Colony, TX 75056',
    city: 'The Colony',
    metro: 'dfw',
    lat: 33.10323,
    lng: -96.89127,
    website: 'https://www.allegiancetattootx.com',
  }),
  shop(17, {
    name: 'Lucky Horseshoe Tattoo',
    slug: 'lucky-horseshoe-tattoo',
    address: '1426 N Main St, Fort Worth, TX 76164',
    city: 'Fort Worth',
    metro: 'dfw',
    lat: 32.77892,
    lng: -97.34719,
  }),
  shop(18, {
    name: 'Harm The Karma Art Collective',
    slug: 'harm-the-karma',
    address: '1465 W Magnolia Ave, Fort Worth, TX 76104',
    city: 'Fort Worth',
    metro: 'dfw',
    lat: 32.73059,
    lng: -97.34161,
  }),
  shop(19, {
    name: 'Dark Age Tattoo Studio',
    slug: 'dark-age-tattoo',
    address: '124 W Oak St, Denton, TX 76201',
    city: 'Denton',
    metro: 'dfw',
    lat: 33.21586,
    lng: -97.13352,
  }),
  shop(20, {
    name: 'Cowboys Tattoo',
    slug: 'cowboys-tattoo',
    address: '211 N Tennessee St, McKinney, TX 75069',
    city: 'McKinney',
    metro: 'dfw',
    lat: 33.19834,
    lng: -96.61512,
  }),
  shop(21, {
    name: 'Legend Tattoo & Piercing',
    slug: 'legend-tattoo-piercing',
    address: '8801 Main St, Frisco, TX 75034',
    city: 'Frisco',
    metro: 'dfw',
    lat: 33.15103,
    lng: -96.80633,
  }),
  shop(22, {
    name: 'Lizards Ink Tattoo & Piercing',
    slug: 'lizards-ink',
    address: '1428 K Ave, Plano, TX 75074',
    city: 'Plano',
    metro: 'dfw',
    lat: 33.01927,
    lng: -96.69914,
  }),
  shop(23, {
    name: 'Creative Tattoo',
    slug: 'creative-tattoo',
    address: '2425 W Walnut St Ste 218, Garland, TX 75042',
    city: 'Garland',
    metro: 'dfw',
    lat: 32.91644,
    lng: -96.66433,
  }),
  shop(24, {
    name: 'Arlington Ink',
    slug: 'arlington-ink',
    address: '1129 E Abram St, Arlington, TX 76010',
    city: 'Arlington',
    metro: 'dfw',
    lat: 32.7354,
    lng: -97.09486,
  }),
  shop(25, {
    name: "Urban's Tattoo & Piercing",
    slug: 'urbans-tattoo-piercing',
    address: '2301 N Collins St #112, Arlington, TX 76011',
    city: 'Arlington',
    metro: 'dfw',
    lat: 32.77425,
    lng: -97.097,
  }),

  // ── Austin metro ──────────────────────────────────────────────
  shop(26, {
    name: 'All Saints Tattoo',
    slug: 'all-saints-tattoo',
    address: '1706 E 6th St, Austin, TX 78702',
    city: 'Austin',
    metro: 'austin',
    lat: 30.26234,
    lng: -97.72369,
  }),
  shop(27, {
    name: 'Black Dagger Tattoo',
    slug: 'black-dagger-tattoo',
    address: '1223 Rosewood Ave, Austin, TX 78702',
    city: 'Austin',
    metro: 'austin',
    lat: 30.26852,
    lng: -97.7256,
  }),
  shop(28, {
    name: 'Sacrament Tattoo & Gallery',
    slug: 'sacrament-tattoo',
    address: '503 E 6th St Ste C, Austin, TX 78701',
    city: 'Austin',
    metro: 'austin',
    lat: 30.26646,
    lng: -97.73813,
  }),
  shop(29, {
    name: 'True Blue Tattoo & Piercing',
    slug: 'true-blue-tattoo',
    address: '607 Red River St, Austin, TX 78701',
    city: 'Austin',
    metro: 'austin',
    lat: 30.26695,
    lng: -97.73677,
    website: 'https://www.truebluetattoo.com',
  }),
  shop(30, {
    name: 'Great Wave Tattoo',
    slug: 'great-wave-tattoo',
    address: '4634 Burnet Rd, Austin, TX 78756',
    city: 'Austin',
    metro: 'austin',
    lat: 30.31784,
    lng: -97.74031,
    website: 'https://www.greatwavetattoo.com',
  }),
  shop(31, {
    name: 'Perfection Tattoo',
    slug: 'perfection-tattoo',
    address: '4205 Guadalupe St, Austin, TX 78751',
    city: 'Austin',
    metro: 'austin',
    lat: 30.30776,
    lng: -97.73466,
    website: 'https://perfectiontattoo.com',
  }),
  shop(32, {
    name: "Mom's Tattoos",
    slug: 'moms-tattoos',
    address: '1703 S Lamar Blvd, Austin, TX 78704',
    city: 'Austin',
    metro: 'austin',
    lat: 30.25044,
    lng: -97.7656,
  }),
  shop(33, {
    name: 'Black Crown Studios',
    slug: 'black-crown-studios',
    address: '8534 S Congress Ave Ste B #220, Austin, TX 78745',
    city: 'Austin',
    metro: 'austin',
    lat: 30.17274,
    lng: -97.78544,
  }),
  shop(34, {
    name: 'All Saints Tattoo North',
    slug: 'all-saints-tattoo-north',
    address: '8303 Burnet Rd, Austin, TX 78757',
    city: 'Austin',
    metro: 'austin',
    lat: 30.36335,
    lng: -97.72848,
    website: 'https://www.allsaintstattoo.com',
  }),
  shop(35, {
    name: 'True Blue Tattoo — Airport Blvd',
    slug: 'true-blue-tattoo-airport',
    address: '4507-B Airport Blvd, Austin, TX 78751',
    city: 'Austin',
    metro: 'austin',
    lat: 30.30338,
    lng: -97.71562,
    website: 'https://www.truebluetattoo.com',
  }),
];

export const ARTISTS: SeedArtist[] = [
  artist(1, {
    name: 'Oliver Peck',
    slug: 'oliver-peck',
    styles: ['traditional'],
    shopSlugs: ['elm-street-tattoo'],
    // Shop co-owner; tattoos part-time only.
    acceptingClients: false,
  }),
  artist(2, {
    name: 'Dean Williams',
    slug: 'dean-williams',
    styles: ['traditional'],
    shopSlugs: ['elm-street-tattoo'],
  }),
  artist(3, {
    name: 'Char McGaughy',
    slug: 'char-mcgaughy',
    styles: ['realism', 'blackwork'],
    shopSlugs: ['gold-dust-tattoos'],
  }),
  artist(4, {
    name: 'Rudy Hetzer IV',
    slug: 'rudy-hetzer-iv',
    styles: ['realism', 'lettering'],
    shopSlugs: ['dallas-tattoo-arts-company'],
  }),
  artist(5, {
    name: 'Deanna James',
    slug: 'deanna-james',
    styles: ['realism'],
    shopSlugs: ['eden-body-art-studio'],
  }),
  artist(6, {
    name: 'Liz Cook',
    slug: 'liz-cook',
    styles: ['realism', 'color'],
    shopSlugs: ['rebel-muse-tattoo'],
  }),
  artist(7, {
    name: 'David Mushaney',
    slug: 'david-mushaney',
    styles: ['realism'],
    shopSlugs: ['rebel-muse-tattoo'],
  }),
  artist(8, {
    name: 'Tray Bale',
    slug: 'tray-bale',
    styles: [],
    shopSlugs: ['rebel-muse-tattoo'],
  }),
  artist(9, {
    name: 'Jay Joree',
    slug: 'jay-joree',
    styles: ['neo-traditional'],
    shopSlugs: ['third-eye-gallery'],
  }),
  artist(10, {
    name: 'Linda Bishop',
    slug: 'linda-bishop',
    styles: ['blackwork'],
    shopSlugs: ['koneko-studio'],
  }),
  artist(11, {
    name: 'Jason Call',
    slug: 'jason-call',
    styles: ['geometric'],
    shopSlugs: ['pristine-ink'],
  }),
  artist(12, {
    name: 'Bri Leflore',
    slug: 'bri-leflore',
    styles: ['fine-line', 'blackwork', 'color'],
    shopSlugs: ['lady-magnolia'],
  }),
  artist(13, {
    name: 'Tiffer Wright',
    slug: 'tiffer-wright',
    styles: ['neo-traditional'],
    shopSlugs: ['folklore-trading-co'],
  }),
  artist(14, {
    name: 'Billy Weigler',
    slug: 'billy-weigler',
    styles: ['illustrative', 'color'],
    shopSlugs: ['folklore-trading-co'],
  }),
  artist(15, {
    name: 'Ejay',
    slug: 'ejay',
    styles: ['geometric', 'blackwork'],
    shopSlugs: ['singleton-tattoo'],
  }),
  artist(16, {
    name: 'Rosa',
    slug: 'rosa',
    styles: ['fine-line'],
    shopSlugs: ['singleton-tattoo'],
  }),
  artist(17, {
    name: 'Billy Jack',
    slug: 'billy-jack',
    styles: [],
    shopSlugs: ['artistic-encounter'],
  }),
  artist(18, {
    name: 'Stephanie Gunter',
    slug: 'stephanie-gunter',
    styles: [],
    shopSlugs: ['artistic-encounter'],
  }),
  artist(19, {
    name: 'Dru Bias',
    slug: 'dru-bias',
    styles: ['japanese', 'traditional'],
    shopSlugs: ['allegiance-tattoo'],
  }),
  artist(20, {
    name: 'Danielle Marie',
    slug: 'danielle-marie',
    styles: ['japanese', 'traditional', 'blackwork'],
    shopSlugs: ['allegiance-tattoo'],
  }),
  artist(21, {
    name: 'Nick Alvarez',
    slug: 'nick-alvarez',
    styles: ['japanese'],
    shopSlugs: ['allegiance-tattoo'],
  }),
  artist(22, {
    name: 'Dan Juarez',
    slug: 'dan-juarez',
    styles: ['realism'],
    shopSlugs: ['dark-age-tattoo'],
  }),
  artist(23, {
    name: 'Ivan Rueda',
    slug: 'ivan-rueda',
    styles: ['realism'],
    shopSlugs: ['dark-age-tattoo'],
  }),
  artist(24, {
    name: 'AJ Maloney',
    slug: 'aj-maloney',
    styles: ['traditional', 'japanese', 'blackwork'],
    shopSlugs: ['black-dagger-tattoo'],
  }),
  artist(25, {
    name: 'Jason Brooks',
    slug: 'jason-brooks',
    styles: ['japanese', 'traditional'],
    shopSlugs: ['great-wave-tattoo'],
  }),
  artist(26, {
    name: 'Chris Trevino',
    slug: 'chris-trevino',
    styles: ['japanese'],
    shopSlugs: ['perfection-tattoo'],
  }),
  artist(27, {
    name: 'Johny Vasquez',
    slug: 'johny-vasquez',
    styles: ['realism', 'fine-line', 'blackwork'],
    shopSlugs: ['black-crown-studios'],
  }),
  artist(28, {
    name: 'Dougie Mittz',
    slug: 'dougie-mittz',
    styles: ['realism', 'blackwork'],
    shopSlugs: ['all-saints-tattoo'],
  }),
];
